backend:
  name: git-gateway
  branch: master

media_folder: static/img
public_folder: /img

collections:
  - name: "post"
    label: "post"
    folder: "src/pages/posts"
    create: true
    slug: "{{day}}-{{month}}-{{year}}-{{slug}}"
    editor:
     preview: false
    fields:
      - name: pathname
        label: Page pathname
        widget: pathname